export const inspectos = {
  slug: "inspectos",
  title: "Inspectos",
  tagline: "",
  status: "live",
  featured: false,
  year: 2023,
  thumbnail: "",
  tags: [],
  summary: "",
  problem: "",
  goals: [],
  constraints: [],
  solution: "",
  architecture: "",
  decisions: [],
  challenges: [],
  results: [],
  lessonsLearned: [],
  futureImprovements: [],
  links: {
    live: "",
    github: "",
  },
};
